/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   saved-request-editor.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../polymer/types/lib/legacy/class.d.ts" />
/// <reference path="../iron-resizable-behavior/iron-resizable-behavior.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-checkbox/paper-checkbox.d.ts" />
/// <reference path="../paper-input/paper-input.d.ts" />
/// <reference path="../paper-input/paper-textarea.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../paper-chip-input/paper-chip-input.d.ts" />
/// <reference path="../iron-form/iron-form.d.ts" />
/// <reference path="../iron-collapse/iron-collapse.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../projects-list-consumer-mixin/projects-list-consumer-mixin.d.ts" />

declare namespace UiElements {

  /**
   * A dialog to edit request meta data.
   *
   * It requires `<request-model>` and `<project-model>` to be in the DOM to
   * handle data queries.
   *
   * ## Usage
   *
   * Assign `request` proeprty to a request obejct. The component decides
   * what view to render (saved vs. not saved request).
   *
   * ```html
   * <saved-request-editor request='{...}'></saved-request-editor>
   * ```
   *
   * If the request has both `_id` and `_rev` proeprties (PouchDB properties)
   * it renders "saved" view.
   *
   * ### Styling
   *
   * `<saved-request-editor>` provides the following custom properties and mixins
   * for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--saved-request-editor` | Mixin applied to the element | `{}`
   * `--saved-request-editor-color` | Color of the element | `inherit`
   * `--saved-request-editor-background-color` | Background color of the element | `inherit`
   * `--saved-request-editor-padding` | Padding of the element. | ``
   * `--saved-request-editor-options-color` | Additional options section color | `rgba(0, 0, 0, 0.74)`
   * `--saved-request-editor-caption-icon-color` | Color of the icon to toggle options | `rgba(0, 0, 0, 0.74)`
   * `--saved-request-editor-caption-icon` | `Mixin applied to toggle options icon` | ``
   * `--saved-request-editor-action-button-color` | Color of action button | `--primary-color`
   * `--saved-request-editor-action-button-background-color` | Background color of action button | ``
   * `--saved-request-editor-action-buttons` | Mixin applied to action buttons | ``
   */
  class SavedRequestEditor extends
    Polymer.IronResizableBehavior(
    ArcComponents.ProjectsListConsumerMixin(
    Object)) {

    /**
     * The request object to be saved / updated in the datastore.
     * It's not required for the editor to work.
     * This object will be attached to `save-request` object as a reference.
     * When this object change it computes values for `name`, `isSaved`,
     * `isDrive`, `projectName` and `projectId` properties.
     */
    request: object|null|undefined;

    /**
     * Name of the request.
     */
    name: string|null|undefined;

    /**
     * Request description.
     */
    description: string|null|undefined;

    /**
     * Should be set if the request has been already saved in the datastore.
     * Adds UI controls to override or save as new.
     */
    readonly isSaved: boolean|null|undefined;

    /**
     * True when saving request to Google Drive.
     */
    isDrive: boolean|null|undefined;

    /**
     * Set if the user chooses to override current request.
     */
    readonly override: boolean|null|undefined;

    /**
     * True when additional options are opened.
     */
    additionalOptionsOpened: boolean|null|undefined;

    /**
     * List of selected in the dialog project names.
     */
    selectedProjects: Array<String|null>|null;
    connectedCallback(): void;

    /**
     * Resets the state of the UI
     */
    reset(): void;

    /**
     * Sends the `cancel-request-edit` custom event to cancel the edit.
     */
    _cancel(): void;

    /**
     * Sets `override` to `false` and sends the form.
     */
    _save(): void;

    /**
     * Sets `override` to `true` and sends the form.
     */
    _override(): void;

    /**
     * Validates and submits the form.
     */
    _sendForm(): void;

    /**
     * Sends the `save-request` custom event with computed detail object.
     */
    _formSubmit(e: CustomEvent|null): void;

    /**
     * Computes `save-request` custom event's `detail` object
     *
     * @returns A detail property of the event.
     */
    _computeEventDetail(): object|null;
    _toggleOptions(): void;

    /**
     * Computes value for `isSaved` property.
     *
     * @param request Request object assigned to the `request`
     */
    _computeIsSaved(request: object|null): Boolean|null;
    _requestChanged(request: any, projects: any): void;

    /**
     * Notifies resize when the height of autogrow textarea changes.
     */
    _autogrowCheckResize(): void;
  }
}

interface HTMLElementTagNameMap {
  "saved-request-editor": UiElements.SavedRequestEditor;
}
