/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   saved-request-editor.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {SavedRequestDetail} from '@advanced-rest-client/saved-request-detail';

import {html, css} from 'lit-element';

import {ProjectsListConsumerMixin} from '@advanced-rest-client/projects-list-consumer-mixin/projects-list-consumer-mixin.js';

declare namespace UiElements {

  /**
   * A dialog to edit request meta data.
   *
   * It requires `<request-model>` and `<project-model>` to be in the DOM to
   * handle data queries.
   *
   * ## Usage
   *
   * Assign `request` proeprty to a request obejct. The component decides
   * what view to render (saved vs. not saved request).
   *
   * ```html
   * <saved-request-editor request='{...}'></saved-request-editor>
   * ```
   *
   * If the request has both `_id` and `_rev` proeprties (PouchDB properties)
   * it renders "saved" view.
   *
   * ### Styling
   *
   * `<saved-request-editor>` provides the following custom properties and mixins
   * for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--saved-request-editor` | Mixin applied to the element | `{}`
   * `--saved-request-editor-color` | Color of the element | `inherit`
   * `--saved-request-editor-background-color` | Background color of the element | `inherit`
   * `--saved-request-editor-padding` | Padding of the element. | ``
   * `--saved-request-editor-options-color` | Additional options section color | `rgba(0, 0, 0, 0.74)`
   * `--saved-request-editor-caption-icon-color` | Color of the icon to toggle options | `rgba(0, 0, 0, 0.74)`
   * `--saved-request-editor-caption-icon` | `Mixin applied to toggle options icon` | ``
   * `--saved-request-editor-action-button-color` | Color of action button | `--primary-color`
   * `--saved-request-editor-action-button-background-color` | Background color of action button | ``
   * `--saved-request-editor-action-buttons` | Mixin applied to action buttons | ``
   */
  class SavedRequestEditor extends
    Polymer.IronResizableBehavior(
    ProjectsListConsumerMixin(
    Object)) {

    /**
     * Name of the request.
     */
    name: string|null|undefined;

    /**
     * Request description.
     */
    description: string|null|undefined;

    /**
     * True when saving request to Google Drive.
     */
    isDrive: boolean|null|undefined;

    /**
     * Set if the user chooses to override current request.
     */
    _override: boolean|null|undefined;

    /**
     * True when additional options are opened.
     */
    additionalOptionsOpened: boolean|null|undefined;

    /**
     * List of selected in the dialog project names.
     */
    selectedProjects: Array<String|null>|null;
    _saving: boolean|null|undefined;
    _titleTemplate(): any;
    _descriptionTemplate(): any;
    _projectsTemplate(): any;
    _additionalActionsTemplate(): any;
    _actionsTemplate(): any;
    render(): any;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _projectsChanged(): void;
    _requestChangedHandler(e: any): void;

    /**
     * Resets the state of the UI
     */
    reset(): void;

    /**
     * Sends the `cancel` custom event to cancel the edit.
     */
    _cancel(): void;

    /**
     * Sets `override` to `false` and sends the form.
     */
    _save(): void;

    /**
     * Sets `override` to `true` and sends the form.
     */
    _overrideHandler(): void;

    /**
     * Validates and submits the form.
     */
    _sendForm(): void;

    /**
     * Sends the `save-request` custom event with computed detail object.
     */
    _formSubmit(e: CustomEvent|null): any;

    /**
     * Computes `save-request` custom event's `detail` object
     *
     * @returns A detail property of the event.
     */
    _computeEventDetail(): object|null;
    _toggleOptions(): void;

    /**
     * Computes value for `isSaved` property.
     *
     * @param request Request object assigned to the `request`
     */
    _computeIsSaved(request: object|null): Boolean|null;
    _requestChanged(request: any): void;
    _restoreProjects(request: any): void;
    _stopEvent(e: any): void;
    _inputChanged(e: any): void;
    _projectsHandler(e: any): void;
    _isDriveHandler(e: any): void;
    _editorValueChanged(e: any): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "saved-request-editor": UiElements.SavedRequestEditor;
  }
}
